# Declare the compilation
CC = gcc

# Declare the output
all: main_Uyen_E4.out

# Compile the exercise TP3.1
main_Uyen_E4.out: main_Uyen_E4.c
	$(CC) $(CFLAGS) -o $@ $<

#Clean all executed files
clean:
	rm -f *.o *.out

